networks:
  zipquote-net:
    external: true
    name: zipquote_zipquote-net

services:
  mcp-server:
    build: .
    restart: always
    mem_limit: 256m
    cpus: 0.5
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      MCP_HOST: 0.0.0.0
      MCP_PORT: 8000
      OPENAI_APPS_CHALLENGE_TOKEN: TwPNKKx9F5AG7FnejR3SPD6N40EqJjx8F-D_ohS1tbs
    networks:
      - zipquote-net
